---
- name: create service for deployment
  hosts: Kubernetes
  # become: true
  user: ec2-user

  tasks:
  - name: get all the k8s settings
    command: kubectl get all

  - name: get the exposed url
    command: minikube service my-goweb-service

